package com.themovieguide.domain.model

import com.themovieguide.domain.utils.EMPTY

data class MovieEntity(
    val adult: Boolean? = false,
    val backdropPath: String? = EMPTY,
    val belongsCollection: BelongsCollectionEntity? = BelongsCollectionEntity(),
    val budget: Int? = 0,
    val genres: List<GenreEntity>? = emptyList(),
    val homepage: String? = EMPTY,
    val id: Int? = 0,
    val imdbId: String? = EMPTY,
    val originalLang: String? = EMPTY,
    val originalTitle: String? = EMPTY,
    val overview: String? = EMPTY,
    val popularity: Double? = 0.0,
    val posterPath: String? = EMPTY,
    val prodCompanies: List<ProductionCompanyEntity>? = emptyList(),
    val prodCountries: List<ProductionCountryEntity>? = emptyList(),
    val releaseDate: String? = EMPTY,
    val revenue: Int? = 0,
    val runtime: Int? = 0,
    val spokenLang: List<LanguageEntity>? = emptyList(),
    val status: String? = EMPTY,
    val tagline: String? = EMPTY,
    val title: String? = EMPTY,
    val video: VideosEntity? = VideosEntity(),
    val voteAverage: Double? = 0.0,
    val voteCount: Int? = 0,
) {
    constructor() : this(
        adult = false,
        backdropPath = EMPTY,
        belongsCollection = BelongsCollectionEntity(),
        budget = 0,
        genres = emptyList(),
        homepage = EMPTY,
        id = 0,
        imdbId = EMPTY,
        originalLang = EMPTY,
        originalTitle = EMPTY,
        overview = EMPTY,
        popularity = 0.0,
        posterPath = EMPTY,
        prodCompanies = emptyList(),
        prodCountries = emptyList(),
        releaseDate = EMPTY,
        revenue = 0,
        runtime = 0,
        spokenLang = emptyList(),
        status = EMPTY,
        tagline = EMPTY,
        title = EMPTY,
        video = VideosEntity(),
        voteAverage = 0.0,
        voteCount = 0,
    )
}
